### ISSUE TITLE
FEAT: Add support for ClickHouse

### ISSUE THREAD

**Issue by alexey-milovidov** [dbgate/dbgate#104]
**Is your feature request related to a problem? Please describe.**
There is no ClickHouse in the list of supported DBMS.

**Describe the solution you'd like**
Add support for ClickHouse.

**Describe alternatives you've considered**
I can get it working through MySQL compatibility layer that ClickHouse provides, but the listing of databases and tables does not work due to lack of INFORMATION_SCHEMA database. Custom queries work fine.

**Additional context**
https://clickhouse.tech/

**Comment by janproch** [comment]
Thanks for tip...

Current DB addition plan looks like:

1. SQLite
2. Oracle
3. ClickHouse

**Comment by beeflyme** [comment]
any update? as our team also using clickhouse.

**Comment by Drabuna** [comment]
Indeed, you can get pretty far with the MySQL compatibility layer.
You have to connect through Clickhouse MySQL port `9004`, and use `password_double_sha1_hex` for the user's password, otherwise it won't work.
All of the queries work fine, you can insert/create/select, `SHOW/USE` etc.
Unfortunately, UI seems to fail on all features.
Would be great to have!

![image](https://user-images.githubusercontent.com/54286/222153117-d9c051a9-f40b-47cc-ad80-9dad85924ab7.png)

**Comment by mbrekhov** [comment]
+1 for this feature(clickhouse)

**Comment by janproch** [comment]
The first version of ClickHouse support is implemented in latest BETA version, https://github.com/dbgate/dbgate/releases/tag/v5.4.5-beta.2

ClickHouse support is available in Community (Free and opensource) edition
