### ISSUE TITLE
date display timezone - how to change?

### ISSUE THREAD

**Issue by jij** [dbgate/dbgate#137]
Connected to MSSQL, ran a query 

> select datecolumn from table where datecolumn >= '05/01/2021' order by datecolumn

but date columns in result tab appears to be casted to some timezone, screenshot below. 

![2021-06-24_15-13-47](https://user-images.githubusercontent.com/1476614/123321715-56a0e280-d501-11eb-95a7-5f2034bb36ba.png)

Is there a way to change this behavior? Ran the same query in SSMS, first row is "05/01/2021" as expected

Thanks

**Comment by janproch** [comment]
Thanks for reporting. Dastes should be displayed exactly as in database, this is bug. If the type of column is not datetimeoffset (with timezone), converting to different timezone has not sense. Also in case of using datetimeoffset, probably better is to show exactly what is stored in DB

Will be fixed in next version

**Comment by janproch** [comment]
Display is changed

TODO underlying driver should return 2020-04-02T03:55:00.043 instead of 2020-04-02T03:55:00.043Z (as it has no information about timezone)

**Comment by janproch** [comment]
This issue is fixed in newest beta, 4.2.7-beta.1 . Release with this fix will be in 2 weeks.

**Comment by janproch** [comment]
Fixed in 4.2.7

**Comment by czhrf** [comment]
> Fixed in 4.2.7

i found the same bug with oracle db using the latest version.
