### ISSUE TITLE
BUG: Table explorer no longer loading

### ISSUE THREAD

**Issue by tvarsis** [dbgate/dbgate#175]
I updated from 4.2.4 to 4.3.1, and after that the table explorer does not load at all. No errors in dev console either. I'm connected to the db correctly and can still run queries etc.

![image](https://user-images.githubusercontent.com/10090010/135755409-540c9bee-d8f4-41db-8a3f-1339e7c5dc89.png)

 - OS: OpenSUSE Tumbleweed
 - App Version 4.3.1
 - Install source Appimage x86
 - Database engine: PostgreSQL 13.4

**Comment by janproch** [comment]
Thank you for the report

I have replicated this issue, when I created index on expression ( https://www.postgresql.org/docs/9.1/indexes-expressional.html )

Version 4.2.4 didn't have analysing PostgreSQL indexes, so there was not problem with this

This issue is fixed in BETA 4.3.2-beta.1 . I believe this should solve issue you reported, but if you could verify it, it will be great

**Comment by tvarsis** [comment]
Yeah, that fixed it. Impressed by your fast response and action, as always! Thanks!
