### ISSUE TITLE
FEAT: Make Ctrl + P and other searches fuzzy

### ISSUE THREAD

**Issue by KBulmer** [dbgate/dbgate#246]
**Is your feature request related to a problem? Please describe.**
Finding tables is time consuming and unintuitive.

**Describe the solution you'd like**
Fuzzy search. A query like "pltr" should suggest the table **Pl**aylist**Tr**ack.

**Additional info**
Ctrl + P in VSCode clearly demonstrates what kind of search I'm looking for.

**Comment by janproch** [comment]
Interseting idea, thanks.

Already now is possible to search multiple substrings (almost fuzzy...), if you type "pl tr", it will find PlaylistTrack  
I will consider this, so that space delimiting will be not neccessary

**Comment by superDuperCyberTechno** [comment]
Ctrl-P also seems to have an unintended side effect where it includes databases in a cluster even though I have ticked "Use only database (...)" in the "Add connection" modal.

In addition, Ctrl-P also only seems to include tables from the currently active database. It would be doubly awesome if it included all databases (respecting my first point) as well as all tables within them.

IE: Say I'm in database A, table B and I need to go to database B, table C. - In my dream scenario I would simply slap Ctrl-P and write "b.c" and hit enter.

**Comment by janproch** [comment]
Fuzzy search implemented in v. 4.7.4

Also fixed problem with including other databases, when connection is marked as single-database

Searching in other databases with Ctrl+P is now not easy, because it will require to load table list from other databases. Maybe it could be done with client-side structure caching (using similar trick, as when you search db name in disconnected server connections). I will consider this...

**Comment by janproch** [comment]
This should be reconsidered, search results are now too big (feedback from more users)

Probably fuzzy search should be used only in Ctrl+P search, and it should also sort results by relevance

**Comment by janproch** [comment]
Better fuzzy search released in 5.2.0
