### ISSUE TITLE
QUESTION: How to provision settings

### ISSUE THREAD

**Issue by mbrevda** [dbgate/dbgate#304]
**Details:**
How can settings be pre-provisioned? The use case is packaging dbgate in an ephemeral docker container, as part of a dev stack. It would be useful to pre-set certain settings, such as theme or auto-refresh. This is currently doable for connections, can it be done for other settings, too?

**Version Information [might be relevant to your issue]**
Operating System: docker

Thanks!

**Comment by janproch** [comment]
I implemented parsing env variable SETTINGS_[setting key], described in docs, will be in BETA soon

* SETTINGS_[settings key] - preconfigure settings value. Setting key could be listed from source codes, https://github.com/dbgate/dbgate/blob/master/packages/web/src/settings/SettingsModal.svelte , find string "name="/ If you need to define "true", use value "1". If you need "false", use empty string ("0" will not work)

This could be not used for configure theme, because theme in web version is stored locally on client machine, and is not define in settings (so each user could have different theme)

**Comment by janproch** [comment]
Released in version 5.0.8

**Comment by mbrevda** [comment]
Awesome, thanks! Going to test next week!

**Comment by mbrevda** [comment]
any changes re being able to provision the theme?
