### ISSUE TITLE
BUG: Switch to form and back to table rows missing

### ISSUE THREAD

**Issue by susnick** [dbgate/dbgate#343]
**Describe the bug**
if you open a table, and then click New row, switching to form and back again breaks. Clicking refresh does not even bring the rows back. You have to close the tab and reopen.

**To Reproduce**
1. Open any table
2. Click New row
3. Click Switch to form
4. Click Switch to table

**Expected behavior**
Expect to see the rows of the table.

**Screenshots**
![image](https://user-images.githubusercontent.com/1975526/184465017-2c7f9f9e-224b-45c0-a5de-935b72f5c968.png)

![image](https://user-images.githubusercontent.com/1975526/184465025-f5bc4f8e-91d6-4d52-8968-a30211ed99c4.png)

**Version Information (please complete the following information):**
 - OS: mac
 - App Version 5.0.0-alpha.1
 - Install source Master branch
 - Type - Web/Application
 - Database engine: MySQL

**Comment by janproch** [comment]
I have replicated this, thanks for error report

The same problem is after clicking refresh, when new rows are inserted.

The reason is, that after inserting new rows, incremental loading is disabled, until saving or reverting changes.

Probably the solution would be to load only first page (100 rows) in this case, so that the table doesn't seem to be empty
