### ISSUE TITLE
BUG: Open query file encoding error

### ISSUE THREAD

**Issue by diegomesata** [dbgate/dbgate#376]
I write a query, with some charactes like ñ, á, é, í, ó, ú, ç

![image](https://user-images.githubusercontent.com/757749/191038019-16025742-8ce1-4aa3-a8c5-9d75f86d1f46.png)

I save the query to the disk.

![image](https://user-images.githubusercontent.com/757749/191038136-8c5e870c-15a4-4204-8e81-ea99b2fa223f.png)

I reopen the query into dbgate, the characters are lost.

![image](https://user-images.githubusercontent.com/757749/191038231-a83f2f09-a098-423b-9ee1-8067c4ffff67.png)

If I open the file in notepad++ the characters are ok, and the file encoding is UTF-8, I think the problem is in the open encoding options.

![image](https://user-images.githubusercontent.com/757749/191038649-4a9bed96-9558-445d-a3c3-a9f8df08c3e6.png)

I know, I am a nightmare, jajaja, thank you for your patience, you have a great product here.

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 5.1.2-beta5
 - Install source Installer
 - Type - Application
 - Database engine: Any

**Comment by janproch** [comment]
Sorry I could not reproduce this. I checked the code, utf-8 encoding is specified while loading.

If you use this query:
```sql
select 'ěšřšěřšřš'
with some charactes like ñ, á, é, í, ó, ú, ç
select 'ěšřšěřšřš'
with some charactes like ñ, á, é, í, ó, ú, ç
```

how the reopened file would seem? Please attach also screenshot of reopened file.

Thank you

**Comment by crile** [comment]
Same problem while I open a sql file.

My file is encoded in utf-8, however, when I open it in dbgate (`File > open`), the character `ç` is replaced by `C'`.

Example with `file.sql`
```
INSERT INTO users (name) VALUES ('François')
```
Become
```
INSERT INTO users (name) VALUES ('FranC'ois')
```
So the execution failed.

---
Version: 5.1.5
Build date: 2022-10-15

**Comment by crile** [comment]
The problem doesn't appear in version 4.3.2. I don't know when it breaks.

**Comment by KKishikawa** [comment]
( #634　#640 ) are also thought to be due to the same causes.

## The bug appears to be caused by character encoding.

The current process detects the encoding only by the File BOM when opening the .sql.
https://github.com/dbgate/dbgate/blob/843675a056191b96c21f0c970b2ed0b245f7d790/packages/web/src/utility/openElectronFile.ts#L47

However, BOM for utf8 files is not recommended.
https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-with-bom


### You can reproduce this by following these steps.
(File attached for testing. It is written in non-ascii characters and saved in utf-8 with/without BOM)
[sample-sqls.zip](https://github.com/dbgate/dbgate/files/13564369/sample-sqls.zip)
env: Electron
1. File > Open
2. Selecting `sample_uff8.sql` (or `sample_utf8withBOM.sql`) and open

| `sample_utf8.sql` | `sample_utf8withBOM.sql` |
|:-:|:-:|
| <img width="390" alt="image" src="https://github.com/dbgate/dbgate/assets/40572953/a899fbcd-1057-45f8-a8e5-deedbd42b840"> | <img width="401" alt="image" src="https://github.com/dbgate/dbgate/assets/40572953/43252b4b-90a0-4650-9281-9a5dc8bdaaf7"> |
|Non-ascii characters are garbled.|Unnecessary characters appear at the beginning of lines.|

Due to the complexity of automatically determining multiple encodings, you should probably add an npm package, such as [the VSCode source](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/textfile/common/encoding.ts#L415).

Alternatively, it can be modified to read utf8 deterministically. It seems that in many cases it is sufficient to work correctly with utf8.
