### ISSUE TITLE
FEAT: show JSON content directly in the overview

### ISSUE THREAD

**Issue by Zerotask** [dbgate/dbgate#395]
**Is your feature request related to a problem? Please describe.**
I often have to look/compare some json content and I can't see it, until I click on one specific json field.
![image](https://user-images.githubusercontent.com/20150243/195211457-525f6bf7-9158-49b1-bb26-173c6e3a7956.png)

**Describe the solution you'd like**
Directly output the json content (or at least the beginning of it)

**Comment by janproch** [comment]
Showing JSON directly is now supported only in perspectives (table context menu, "Open perspective" or "design perspective query" in new version), then check JSON column and change column display type to JSON

In next version, JSONs will be automatically displayed as JSON, without need if explicit changing display type

Showing JSON in normal table editor is a bit problem, because this table is designed to have all rows with equal height

![Screenshot 2022-10-08 at 21 14 52](https://user-images.githubusercontent.com/2543891/195532406-906867ba-85db-4de9-be86-e57f647c2851.png)

**Comment by ceymard** [comment]
I would like to reopen this, as even when forcing ::text to try to have it at least display the first characters, I still can't see JSON in the table view, and it is actually a major problem.

It would be very useful to at least have a preview of the json, clicking is way to cumbersome...
