### ISSUE TITLE
Why port 1000 is busy?

### ISSUE THREAD

**Issue by mattskinosix** [dbgate/dbgate#518]
**Details:**
when i start dbgate port 1000 is taken by the client

**Version Information **
Operating System: linux
Vesion 5.2.4

**Comment by ProjectInfinity** [comment]
Which operating system are you using and how do you check that the port is in use?

If you are on Linux, try doing the following in a terminal:
sudo lsof -i:1000

For your information I tested this myself just now and found that port 1000 is not taken by any process on my system.
That said I believe 2 random internal ports should be taken but not 1000 specifically.

**Comment by ProjectInfinity** [comment]
This looks normal to me.

**Comment by janproch** [comment]
For SSH tunneling, first free port between 10000 and 60000 is used

https://github.com/dbgate/dbgate/blob/master/packages/api/src/utility/sshTunnel.js#L68

**Comment by mattskinosix** [comment]
Thank you very much, you are my hero

Il giorno gio 16 mar 2023 alle ore 12:12 Jan Prochazka <
***@***.***> ha scritto:

**Comment by mattskinosix** [comment]
> For SSH tunneling, first free port between 10000 and 60000 is used
> 
> https://github.com/dbgate/dbgate/blob/58f4370bb6c6e18cd98f891714c305346dff2076/packages/api/src/utility/sshTunnel.js#L68

**Comment by gianfrancodemarco** [comment]
Hello, I'm reopening this issue because I've encountered a related problem. Is it possible to configure the port using an environment variable?

In my scenario, I have a development environment that starts multiple containers, and one of them requires port 10000 to be available. I need to remember to close DBGate before launching my environment; otherwise, the startup process will fail, causing a few minutes of wasted time. It would be convenient to configure DBGate's default port settings once and for all.
