### ISSUE TITLE
BUG: Oauth2 in combination with Google doesn't log payload

### ISSUE THREAD

**Issue by timvandruenen** [dbgate/dbgate#727]
**Describe the bug**
Using Google Oauth2 as login method, the `payload` in the logs is always `null`.

Example log after logging in with Google Oauth2:
```
{"pid":1,"caller":"auth","payload":null,"level":30,"msg":"User payload returned from OAUTH","time":1710771853052}
```

**To Reproduce**
Deploy DbGate with Env variables including oauth: https://dbgate.org/docs/env-variables.html

I tried the following scopes (`OAUTH_SCOPE`):
- profile
- email
- openid

Login works as expected. If I configure the scope with something different I receive an error from Google, as expected.

I tried a lot of things in `OAUTH_LOGIN_FIELD`, all without success. Also keeping it empty. DbGate keeps on logging that the payload is null.

https://developers.google.com/identity/protocols/oauth2/scopes#oauth2
https://developers.google.com/identity/protocols/oauth2

**Expected behavior**
Login works + DbGate logs the full payload or the specific payload field configured in `OAUTH_LOGIN_FIELD`.

**Screenshots**
See log above.

**Version Information (please complete the following information):**
 - OS: Linux
 - App Version: v2.5.7
 - Install source: Docker
 - Type - Web
 - Database engine: -

**Comment by alexandrovas** [comment]
Same problem with generic Oauth server

**Comment by yoadey** [comment]
I have the same problem. After some digging in, I think the root cause is this line:

https://github.com/dbgate/dbgate/blob/669ae024f961ff483d2a5df62a2ae4225eb5db25/packages/api/src/auth/authProvider.js#L88

It expects the access_token to be a jwt, but acording to the standard, this may not be the case: https://www.oauth.com/oauth2-servers/access-tokens/

It would be better to check if there is an `id_token` first (which is not directly oauth, but openid) and take the information from this token and only if it doesn't exist, use the `access_token` as a fallback.

But to be more backwards compatible it would also be ok to first try to parse the `access_token` and if that fails fall back to an `id_token`.

I'll go ahead and create a PR for that.
