### ISSUE TITLE
BUG: [MSSQL] Foreign keys show up in a weird way

### ISSUE THREAD

**Issue by savissimo** [dbgate/dbgate#734]
**Describe the bug**
When looking at the structure of a table on a MS-SQL database, the foreign keys are sometimes shown with the referenced columns duplicated several times. 

**To Reproduce**
1. Open a table structure
2. Check the Foreign Keys section
3. Some FKs show a list of columns that contains duplicates. 

**Expected behavior**
No duplicates are shown. 

**Screenshots**
![image](https://github.com/dbgate/dbgate/assets/6923738/67a22b31-ed06-475d-a4e6-420cbe875209)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 5.2.7
 - Install source Installer
 - Type - Application
 - Database engine: SQL Server

**Comment by savissimo** [comment]
Additional info: running the query I found in `plugins/dbgate-plugin-mssql/src/backend/sql/foreignKeys.js` I found multiple rows with the same `constraintName`, which seems to be what is used to group the results (I couldn't find the code that does that though). However, those constraints are relative to different tables in different schemas. If `schemaName`, `pureName` or `columnName` were used to discriminate, the grouping would work. 

There is still an issue (probably caused by bad DB administration on our instance?) that the same constraint (table X column x => table Y column y) appears multiple times in that query. But that is probably a mistake on our side.

**Comment by ezwelty** [comment]
I just stumbled into this bug as well, but with PostgreSQL and on DBGate 6.0. The reason seems to be the same: foreign key constraints with the same name are grouped together, ignoring the tables they apply to or the schema they are in. One of the ramifications of this is that the very handy [+] feature is lost, because DBGate then things it is a compound foreign key rather than a single-column primary key.

**Comment by janproch** [comment]
Fixed for PostgreSQL, will be fixed for MS SQL (I replicated it)
