### ISSUE TITLE
BUG: When in splitview mode and Clicking "Refresh" button on the right side, will refresh the left side, and not the right side

### ISSUE THREAD

**Issue by martinandersen3d** [dbgate/dbgate#810]
**Describe the bug**
BUG: When in splitview mode and Clicking "Refresh" button on the right side, will refresh the left side, and not the right side

**To Reproduce**
BUG: When in splitview mode and Clicking "Refresh" button on the right side, will refresh the left side, and not the right side

**Expected behavior**
Clicking refresh in the right side should refresh the right side

**Screenshots**

**Version Information (please complete the following information):**
 - App Version: 5.2.8

**Comment by janproch** [comment]
This seems to be quite difficult problem, because commands were designed to be singletons...
It will be quite a big refactor to fix this

I created partial solution of this situation, buttons from non-active components are now hidden. If this will appear to be confusing, more complex solution will be added to roadmap
