### ISSUE TITLE
FEAT: Support sqlite(3) files as a data source

### ISSUE THREAD

**Issue by ConstantineK** [dbgate/dbgate#89]
**Describe the solution you'd like**
I would like to apply the features of DbGate to a sqllite file.

**Describe alternatives you've considered**
I have an open feature request for azure data studio to do the same, I use the command line currently (which is fairly capable.)

**Additional context**
Not much, I know that adding a new data format is a big request though, feel free to bug me if you have any questions.

**Comment by ConradSollitt** [comment]
I'm not sure if it would make sense to support, however if possible file drag and drop (or Windows Explorer/Apple Finder right-click and [Open With]) menu would be a really nice feature and useful for end users of DbGate.

In case it helps decide what driver to use here are 3 widely used SQLite packages for npm. `better-sqlite3` uses synchronous API instead of `async\await` and is the fastest of the 3 packages. I've worked with all 3 and recently switched 2 projects to `better-sqlite3` so I would highly recommend it based on performance, one was server side using express and the other a console script.

* https://www.npmjs.com/package/better-sqlite3
* https://www.npmjs.com/package/sqlite3
* https://www.npmjs.com/package/sqlite

**Comment by janproch** [comment]
Thanks for inspiration, I wanted to use sqlite3 package, but better-sqlite3 looks great

Generally I prefer async API, but for db driver for embeded database sync API is OK

Drag & drop should work, today is this implemented for opening excel, csv and sql files

**Comment by janproch** [comment]
Added in version 4.2.0

**Comment by nikvdp** [comment]
Thanks for adding this, I’d been eagerly awaiting sqlite support!

Not sure if this is a bug or intentional behavior, but I was initially unable to open my sqlite db because after selecting sqlite in the new connection dialog the file selector wouldn’t let me select my db file (it was grayed out).

I eventually tried dragging the sqlite file into the dbgate window after which it worked beautifully.

(I’m on an M1 mac running Big Sur in case it’s relevant)

**Comment by ConradSollitt** [comment]
Great job on SQLite Support @janproch 

I've been busy so I didn't try it out yet but just downloaded on my new MacBook Air then dragged and dropped two different SQLite files and DbGate showed all tables! My database is relatively small however the largest table has ~15,000 rows and when scrolling it looks very smooth. I'll be testing on Windows tomorrow or next week and have an older Mac that I can help test if needed.

Unrelated but great job on the font's for the Mac right-click menu. The bold/larger/italic font on shortcut keys is really a nice touch I think; I don't recall seeing this technique used before.

One of my databases has views and they didn't show up. I looked at the code quick and compared with the MySQL plugin and saw that the SQLite code is only getting tables.

https://github.com/dbgate/dbgate/blob/master/plugins/dbgate-plugin-sqlite/src/backend/Analyser.js

```sql
select * from sqlite_master where type='table'
```

Other objects that exist: https://sqlite.org/schematab.html

* 'view'
* 'index'
* 'trigger'

They can all be found by querying `sqlite_master`.

I can help look into adding views or the other objects soon but I might be a week or two before I can make the time.

**Comment by janproch** [comment]
Thanks for feefback @ConradSollitt !

I will add support of views soon, I have forgotten this. About other objects, maybe this would be more complicated, indexes are not yet supported fully in DbGate, but huge improvement of this topic is planned to next milestone - table structure editor.

**Comment by janproch** [comment]
View support added
