### ISSUE TITLE
BUG: Database connection not using pool

### ISSUE THREAD

**Issue by andre-at-situ** [dbgate/dbgate#920]
**Describe the bug**

In Windows versions 5.5.4 and 5.5.5 (community) if a database connection is left open to a ssh connected AWS MySQL RDS instance, then the connection count to the database increases until all available connections are exhausted.

**To Reproduce**
1. Open DbGate 5.5.5.
2. Connect through to a MySQL database on AWS using ssh.
3. Query something to open a connection.
4. Check RDS connection stats. Record number of connections.
5. Let it sit there for 30 minutes.
6. Check RDS connection stats. Record number of connections and view increased number of connection open :(
7. Close DbGate. Watch connections drop to zero.

**Expected behavior**
DbGate should re-use the database's connection pool. This behaviour cannot be replicated in version 5.5.3.

**Screenshots**

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 5.5.5 and 5.5.4
 - Install source: Windows installer
 - Type: Application
 - Database engine: MySQL

**Comment by janproch** [comment]
Thanks, good catch. It should be fixed in 5.5.6-beta.1.

In fact, DbGate doesn't use a classic connection pool, because connection reusing can lead to strange errors. Instead, it uses small number of connections, every connection is used to specific purpose. Connection should be closed after some idle time.

Connections behind SSH tunnel were not correctly closed because of some internal changes in 5.5.4 version, now are connections closed in much cleaner and more effective way.

**Comment by andre-at-situ** [comment]
Will test. Nice response time :)

**Comment by andre-at-situ** [comment]
Yup.. sorted. Many thanks.
